// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BLL.DAL;

[Table("Book")]
public partial class Book
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Name is Required!")]
    [StringLength(255)]
    public string Name { get; set; }

    public short? NumberOfPages { get; set; }


    [Column(TypeName = "datetime")]
    [Required(ErrorMessage = "Date is Required!")]
    public DateTime? PublishDate { get; set; }

    [Required(ErrorMessage = "Price is Required!")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    public bool IsTopSeller { get; set; }

    [Required(ErrorMessage = "Author is Required!")]
    public int? AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("Books")]
    public virtual Author Author { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<BookGenre> BookGenres { get; set; } = new List<BookGenre>();
}