// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLL.DAL;

[Table("User")]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Username is required!")]
    [StringLength(255)]
    public string UserName { get; set; }

    [Required(ErrorMessage = "{0} is required!")]
    [StringLength(255)]
    public string Password { get; set; }

    public bool IsActive { get; set; }

    [Required(ErrorMessage = "Role is Required!")]
    public int RoleId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }
}